[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
